### ISSUE TITLE
Sidebar of GitHub Sponsor (beta) Dashboard is not themed

### ISSUE THREAD

**Issue by blueset** [DarkThemeHub/GithubDarkTheme#101]
**Describe the bug**
Sidebar of GitHub Sponsor Dashboard is not themed. (i.e. in its original white style)

URL: `https://github.com/sponsors/{USERNAME}/dashboard`, e.g. `https://github.com/sponsors/blueset/dashboard`.

**Expected behavior**
Sidebar of GitHub Sponsor Dashboard is themed in dark style.

**Screenshots**
Add screenshot and illustrate the location of bug on the page.

![image](https://user-images.githubusercontent.com/553831/67259009-14223980-f4c6-11e9-96ac-84e913de0cd9.png)
![image](https://user-images.githubusercontent.com/553831/67259031-36b45280-f4c6-11e9-8714-2bebf25990ae.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 77.0.3865.120 on macOS Catalina

**Note**
This GitHub feature is still in beta. 

<details><summary>HTML source of the sidebar.</summary>

```

  <aside class="d-none d-lg-block bg-gray-light border-right" style="min-width:320px;" aria-label="Sponsors dashboard sidebar" >
    <div class="p-4">
      <img alt="" width="70" height="70" class="avatar mx-auto mb-2 d-block" src="https://avatars2.githubusercontent.com/u/{USERID?s=140&amp;v=4" />
      <h2 class="f4 text-normal text-center">{USERNAME}</h2>
    </div>
    <nav class="menu mb-0" style="border-right: 0; border-left: 0; border-radius:0;" aria-label="Sponsors dashboard navigation">
      <div class="border-bottom border-gray-dark">
        <a class="menu-item selected" aria-current="page" href="/sponsors/{USERNAME}/dashboard">
          Overview
            <span class="Label Label--outline float-right border-green text-green">
              Active
            </span>
</a>        <a class="menu-item" href="/sponsors/{USERNAME}/edit">
          Profile bio
          <span class="float-right">
              <svg class="octicon octicon-check text-green" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"/></svg>
          </span>
</a>        <a class="menu-item" href="/sponsors/{USERNAME}/tiers">
          Sponsor tiers
          <span class="float-right">
              <svg class="octicon octicon-check text-green" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"/></svg>
          </span>
</a>      </div>
      <div class="border-top border-gray-dark">
        <a class="menu-item" href="/sponsors/{USERNAME}/list">
          Your sponsors
</a>        <a class="menu-item" href="/sponsors/{USERNAME}/updates">
          Updates
</a>          <a class="menu-item" href="/sponsors/{USERNAME}/payouts">
            <span >
              Payouts
            </span>
</a>        <a class="menu-item" href="/sponsors/{USERNAME}/settings">
           Settings
</a>      </div>
    </nav>
  </aside>
```

</details>

**Comment by acoop133** [comment]
Thanks for providing the html! i will be doing this blind so will need you to confirm the result for me when i get to it :)

just to confirm, you're on the latest version of the theme?

Asking because when i paste the html into my browser, the colours seem to be fine. Although they could have overridden some stuff on the page.
![image](https://user-images.githubusercontent.com/19627023/67340054-76118c00-f524-11e9-8337-ba85417442df.png)

**Comment by blueset** [comment]
I'm testing it with the Oct 21 2019 version on [UserStyles](https://userstyles.org/styles/168350/githubdarktheme).

Just took another closer look at the CSS render of my page, the style is broken due to an outer `div` element with class `MarketplaceEdit-body`. I have updated the HTML source above accordingly to reflect the fact.

This is the CSS rule from GitHub that breaks the dark theme.
![image](https://user-images.githubusercontent.com/553831/67347133-bd733900-f573-11e9-92c0-872451b3d026.png)

**Comment by acoop133** [comment]
Great! thanks

**Comment by acoop133** [comment]
Can you check if this fixes the issue. Edit the theme and just paste the following at the end of the file.

```
.MarketplaceEdit-body .menu-item {
    background: none !important;
}

.MarketplaceEdit-body .menu-item:hover {
    background: #39424A !important;
}
```

**Comment by acoop133** [comment]
Why is sponsor page using style from marketplace.scss... i swear they employ high schoolers to write their styles.

**Comment by blueset** [comment]
It's working now, thanks!
