### ISSUE TITLE
Hint text in “Related issues” is not themed.

### ISSUE THREAD

**Issue by blueset** [DarkThemeHub/GithubDarkTheme#102]
**Describe the bug**
Hint text in “Related issues” is not themed.

Namely:
> “The following issues might be related” on the first line

> “Related issue <kbd>Beta</kbd> [Opt out](#) or [give us feedback](#)” on the last line.

**Expected behavior**
Hint text in “Related issues” is themed in dark style.

**Screenshots**
Add screenshot and illustrate the location of bug on the page.

![image](https://user-images.githubusercontent.com/553831/67259213-32d50000-f4c7-11e9-92c9-e84b6b81e1ab.png)
![image](https://user-images.githubusercontent.com/553831/67259222-3cf6fe80-f4c7-11e9-8bda-e25353477d86.png)

**Desktop (please complete the following information):**
 - Browser: Chrome 77.0.3865.120 on macOS Catalina.

**Comment by acoop133** [comment]
looks like i actually did not commit the fix for this 😣
