### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Sv443** [DarkThemeHub/GithubDarkTheme#108]
**Improvement to be done**
There currently is no license. I would maybe like to contribute / build upon this theme but can't since no license automatically means "all rights reserved".

**Describe the solution you'd like**
Please add a `LICENSE` file to the root directory (even if it's just an all rights reserved license, it's still more clear than having no license at all).

**Comment by acoop133** [comment]
Hi @Sv443   
Your suggestion has prompted me to read more about licensing. However, I have not found the right license for this project. (Im more leaning towards "Source available: non-commercial" type of license, but it seems its not ready to be adopted by the community yet)

You're correct in stating that no license provided automatically means all rights reserved.
However, you're still able to contribute to this repository.
See Github's Policy [6. Contributions Under Repository License](https://help.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license)

If you do decide to make a contribution, your Github name will be displayed in the release note for any contribution of yours that made into the release. (This includes suggestions, bug reporting and code contribution)
https://github.com/DarkThemeHub/GithubDarkTheme/releases


If its a different "flavor" of dark theme you're after, I have had thoughts around how i could support multiple theme "flavors" easily.

Do however update me with what you think is missing from the theme.

I will go ahead and update the license as requested.

**Comment by Sv443** [comment]
Hi @acoop133, there is the [Creative Commons Attribution Non-Commercial (CC-BY-NC) license](https://creativecommons.org/licenses/by-nc/4.0/) which disallows commercial use but is still pretty permissive and still preserves copyright.  
[Here's the license text](https://creativecommons.org/choose/non-web-popup?license_code=by-nc&amp;jurisdiction=&amp;version=4.0&amp;lang=en).

**Comment by acoop133** [comment]
Unfortunately, CC isnt recommended for software licensing.

**Comment by Sv443** [comment]
> 
> 
> Unfortunately, CC isnt recommended for software licensing.
Huh yeah, that's true.
