### ISSUE TITLE
darkify githubusercontent.com

### ISSUE THREAD

**Issue by acoop133** [DarkThemeHub/GithubDarkTheme#116]
Add githubusercontent domain to regex

**Comment by Idomo** [comment]
Please add support also for `https://gist.githubusercontent.com` (for example: https://gist.githubusercontent.com/schedutron/cd925247bfc4f8ae7930bbd99984a441/raw/754d98d3f90a86e3370378ef278ca7e25c4d1e05/chat_serv.py)

**Comment by acoop133** [comment]
Ahh, i will make it for any sub domain then :)
