### ISSUE TITLE
Theme is applied to every URL that contains "GitHub"

### ISSUE THREAD

**Issue by meyer1994** [DarkThemeHub/GithubDarkTheme#120]
**Describe the bug**
The regex in use makes the theme to be applied in every URL that contains the word `github` in it. It is applied to its own [page](https://userstyles.org/styles/168350/githubdarktheme).

The current Regex does not escape the dots:
```^https?://(.*.)?(githubusercontent|github)..*```

It should be:
```^https?://(.*\.)?(githubusercontent|github)\..*```

**Expected behavior**
The theme should only be applied to Github websites. Not every URL that contains `github` in it. 

**Screenshots**
With current regex:
![Imgur](https://i.imgur.com/04vhC6U.png)

With new regex:
![Imgur](https://i.imgur.com/U9y8TuL.png)

**Desktop (please complete the following information):**
 - Browser: 71.0 (64-bit)
 - Stylus: 1.5.6

**Comment by acoop133** [comment]
my bad dude, if you force refresh the style, the fix is already there :P. 

Basically i was hoping to squeeze in the fix (like 10 minutes after releasing ) before anyone updated  :')

Props to you for catching it, I should have just released a new version :D

https://github.com/DarkThemeHub/GithubDarkTheme/blob/be0ca5b2f99fbc25cc32f3729f47603dd57ae3ab/Generated/github.user.styl#L12

**Comment by acoop133** [comment]
i guess i could just release a new version now and problem solved for everyone :D

**Comment by acoop133** [comment]
https://github.com/DarkThemeHub/GithubDarkTheme#option-1-recommended-due-to-privacy-concerns-with-userstylesorg

if you're not already, I would recommend you install this style using the above method due to privacy concerns with userstyles

**Comment by acoop133** [comment]
Ive just updated my work machines theme via userstyles and it seems me updating the content there isnt working.

Regex is unchanged.... and ive tried it twice

Changing regex on its own probably doesnt actually update the file... or their site is having issues with updating files. 

Next time i release some css changes, we'll see if it updates then. ( end of this week )

**Comment by meyer1994** [comment]
Also, it should not apply to `github.io` websites. For example: 

`https://sagioto.github.io/maven2gradle/`

Maybe exclude `io` after the github?

I've created this Regex:

```regex
^https?:\/\/(.*\.)?(githubusercontent|github)\.(?!io).*
```

Testing it with [Regex101](https://regex101.com/r/O0R02h/1) seems to work. Not exhaustive though.

**Comment by acoop133** [comment]
I mean in principal this theme should cover everything github. i would class that as a github site. 
I will theme it instead of excluding it :)

**Comment by acoop133** [comment]
oh wait nvm, im being an idiot.  hahaha

**Comment by acoop133** [comment]
github.io redirects to https://pages.github.com/ so i think we're safe

**Comment by nyuszika7h** [comment]
No, this is still incorrectly applied to subdomains under github.io, which is user-generated content, not part of GitHub, so it should not be styled.

Example of breakage: https://jspenguin2017.github.io/uBlockProtector/

**Comment by meyer1994** [comment]
The new proposed regex seems to work for the `.io` pages.
See this [link](https://regex101.com/r/O0R02h/2)

**Comment by acoop133** [comment]
> github.io redirects to https://pages.github.com/ so i think we're safe

On that note, i should theme that page.

**Comment by acoop133** [comment]
so the end solution hasnt entirely excluded google, it still has an issue when you search `github.com`. ive formulated a new version which should do so but stylus thinks it knows better...

https://regex101.com/r/bW6cYw/3

I however tested it against the work in progress chrome extension and works as expected :)

**Comment by acoop133** [comment]
So its possible that stylus fixed their regex comparer? because new regex works for me now.
