### ISSUE TITLE
Theme applies if URL has "github" at any place

### ISSUE THREAD

**Issue by KrasnovPavel** [DarkThemeHub/GithubDarkTheme#124]
For example theme applies if I search github in google.
![image](https://user-images.githubusercontent.com/5003831/71449398-bc6dac00-275c-11ea-9047-299fca8e393a.png)
URL: https://www.google.com/search?newwindow=1&rlz=1C1CHBF_enRU874RU874&sxsrf=ACYBGNR1vjP6T2ByrudUnIFthHEKkQQmLg%3A1577297831591&ei=p6cDXvTcI6aKk74PoKq1iA4&q=github&oq=github&gs_l=psy-ab.12..0i67l8j0l2.61967.64141..70418...0.2..0.75.149.2......0....1..gws-wiz.......0i71j35i39j0i22i30.AI6gfuUXyqU&ved=0ahUKEwi0zNOntNHmAhUmxcQBHSBVDeEQ4dUDCAs

**Comment by TheFrenchGhosty** [comment]
Duplicate of #120

**Comment by KrasnovPavel** [comment]
Sorry

**Comment by acoop133** [comment]
Get your sweet sweet update! :D
