### ISSUE TITLE
beta notification

### ISSUE THREAD

**Issue by yukulele** [DarkThemeHub/GithubDarkTheme#128]
bug with beta notification (https://github.com/notifications/beta)

Expected behavior:
notification white on white text on mouse hover

![Screenshot_20200107_225540](https://user-images.githubusercontent.com/347244/71932940-40825380-31a1-11ea-86e4-5d5c7facad94.png)

 - Browser Firefox

**Comment by acoop133** [comment]
Ahh, i dont have access to this beta :/ could you provide the css class for that element?

**Comment by acoop133** [comment]
just paste the html into here :)

**Comment by yukulele** [comment]
```
.notifications-list-item.notification-unread {
    background-color: #fff;
}
```
and
```
.notifications-list-item:hover {
    background-color: #f1f8ff !important;
}
```

**Comment by yukulele** [comment]
on https://github.com/notifications you can try beta

**Comment by acoop133** [comment]
Nope lol. It seems they've only rolled it out to some people. Lucky you :P

**Comment by yukulele** [comment]
theire is also this signup message when you are not logged in:
![signup](https://user-images.githubusercontent.com/347244/72008489-3d946b00-3254-11ea-9831-3bd6ff1f6424.png)

**Comment by acoop133** [comment]
> ```css
> .notifications-list-item.notification-unread {
>     background-color: #fff;
> }
> ```
> 
> and
> 
> ```css
> .notifications-list-item:hover {
>     background-color: #f1f8ff !important;
> }
> ```

not sure what uses the `notifications-list-item.notification-unread`.

Do you mind pasting the html for that whole notification list element here, i can paste it in my browser and fix it from there along with that author and commented box :)

![image](https://user-images.githubusercontent.com/19627023/72066493-a0c7e100-32d8-11ea-92e9-65f9ab78e986.png)

**Comment by acoop133** [comment]
Just got access to the beta. no need now.
