### ISSUE TITLE
Theme doesn't work on Community Forum and Shop pages

### ISSUE THREAD

**Issue by voxem** [DarkThemeHub/GithubDarkTheme#131]
The theme does not work properly on the [Community Forum](https://github.community/t5/How-to-use-Git-and-GitHub/Where-do-I-post-feature-requests-for-Github/td-p/15024) and the [Shop](https://github.myshopify.com).

_Community Forum:_
![image](https://user-images.githubusercontent.com/59542429/72205822-9b5cc900-3487-11ea-9747-762b44e53195.png)

_Shop:_
![image](https://user-images.githubusercontent.com/59542429/72205782-3903c880-3487-11ea-8a61-f3bcd554432e.png)

Also, the theme is applied to the [Desktop](https://desktop.github.com) page, but I don't think it's necessary.

**Comment by acoop133** [comment]
will fix Community page (again... sigh.. they keep breaking stuff)
will exclude shopify page since its not github
will exclude desktop as you're correct.
