### ISSUE TITLE
"Similar Comments" and "Hidden Items" widgets are poorly displayed

### ISSUE THREAD

**Issue by forivall** [DarkThemeHub/GithubDarkTheme#138]
**Describe the bug**
There's no little squiggle line 😢  and the background is odd and the text is odd 

**Expected behavior**
There should at least be a little squiggle line 😢

**Screenshots**
https://github.com/Microsoft/TypeScript/pull/29671

![Screen Shot 2020-02-05 at 4 11 01 PM](https://user-images.githubusercontent.com/760204/73894690-24221700-4832-11ea-8479-82b41b67a69b.png)
![Screen Shot 2020-02-05 at 4 10 42 PM](https://user-images.githubusercontent.com/760204/73894693-25ebda80-4832-11ea-989f-2dff26d7a4c7.png)

**Comment by Snazzie** [comment]
🤣  i'll see what i can do.

**Comment by Snazzie** [comment]
So, i do remember trying to keep the squiggly, but the problem was and still is that the squiggly isnt directly override it through css without affecting the parent element.

The only way to show it on a dark background nicely will have to be editing the png and store the png somewhere then override the url with the replacement.

Its not something im ecstatic to do tbh.

I will however make the rest of the elements better looking

**Comment by Snazzie** [comment]
See Visuals section of the release notes for the new look

**Comment by forivall** [comment]
Since a squiggle would be dead simple to do in a small svg, i think a solution could be to embed that (in a dataurl) instead of a png. I also found an example of filtering backgrounds [here](https://codepen.io/forivall/pen/XWbmWoE) via [this stackoverflow answer](https://stackoverflow.com/questions/20039765/how-to-apply-a-css-filter-to-a-background-image).

Your current solution is also good as is, thanks!

**Comment by Snazzie** [comment]
I didnt explain the problem well i think. So the background-url is applied to the parent element of the show more element.

If i were to apply a filter to the class name that houses the background-url, it will apply the filter to all the children of that element and you get the following.
![image](https://user-images.githubusercontent.com/19627023/74283986-d407f080-4d1a-11ea-9c19-a102b4226996.png)

Svg will probably be the solution, but yeah, not to ecstatic to do that 😆
