### ISSUE TITLE
Issues pages in responsive (narrow windows) has white background in some elements

### ISSUE THREAD

**Issue by forivall** [DarkThemeHub/GithubDarkTheme#142]
**Describe the bug**
There's some white background, etc. elements when you make your window narrow on the issues commenting page (roughly less than 950px wide and another breakpoint at around 750 --- found them:
![Screen Shot 2020-02-14 at 12 16 44 PM](https://user-images.githubusercontent.com/760204/74564408-e30dbf00-4f23-11ea-9054-90c38564b35c.png)

**Expected behavior**
the background should be in line with the other dark elements.

**Screenshots**
https://github.com/DarkThemeHub/GithubDarkTheme/issues/new?assignees=&labels=&template=bug_report.md&title=

![Screen Shot 2020-02-14 at 12 10 16 PM](https://user-images.githubusercontent.com/760204/74564173-477c4e80-4f23-11ea-922c-1c5b89aefa5f.png)

Also some bad padding at the narrowest breakpoint (to the right of the "comment" button)
![Screen Shot 2020-02-14 at 12 11 07 PM](https://user-images.githubusercontent.com/760204/74564184-5105b680-4f23-11ea-8192-9cdd18a1413d.png)
(without dark theme, there's no color change that shows this margin)
![Screen Shot 2020-02-14 at 12 11 12 PM](https://user-images.githubusercontent.com/760204/74564209-61b62c80-4f23-11ea-98aa-11b27e3cc79c.png)

And in the add comment page:
![Screen Shot 2020-02-14 at 12 11 34 PM](https://user-images.githubusercontent.com/760204/74564220-6975d100-4f23-11ea-88c7-bcd2613ee6cf.png)

**Comment by Snazzie** [comment]
nice catch

**Comment by Snazzie** [comment]
Can you elaborate on `Also some bad padding at the narrowest breakpoint (to the right of the "comment" button)`

`(without dark theme, there's no color change that shows this margin)`
Do you mean that parent of `Close issue` and `Comment` button should be same colour as background?

**Comment by forivall** [comment]
> Are you saying that the parent of `Close issue` and `Comment` button should be same colour as the page background?
Yeah, that's definitely an option. Otherwise, i'd add some `padding-right` to the parent.
