### ISSUE TITLE
Checkboxes doesn't render correctly

### ISSUE THREAD

**Issue by Akianonymus** [DarkThemeHub/GithubDarkTheme#162]
Both marked and unmarked checkboxes shows as unmarked checkboxes.
* [x] This is checked.
* [ ] This is unchecked.

**Comment by Snazzie** [comment]
[![Screenshot from Gyazo](https://gyazo.com/f198934ea9daf2422099e0dde5c7d815/raw)](https://gyazo.com/f198934ea9daf2422099e0dde5c7d815)

Render correctly for me? Are you on the latest version?

**Comment by Akianonymus** [comment]
> [![Screenshot from Gyazo](https://camo.githubusercontent.com/a325df72f373e42d3e20f359fb43ca5ee1774f85/68747470733a2f2f6779617a6f2e636f6d2f66313938393334656139646166323432323039396530646465356337643831352f726177)](https://gyazo.com/f198934ea9daf2422099e0dde5c7d815)
> 
> Rendering correctly for me? Are you on the latest version?

![Screenshot_20200511-230115](https://user-images.githubusercontent.com/32216346/81592283-5caa3180-93db-11ea-8abc-6fd5efa4d93e.png)

oops, my bad, i was on an old version, just updated it.

Thank you for your theme.

**Comment by Snazzie** [comment]
Just Fyi, if you installed the theme via  userstyles, the theme and auto update is broken due to the way they process the theme file i upload.

Maybe that doesnt apply to you since you're on mobile? Not sure how it works in your situation.

**Comment by Snazzie** [comment]
Ps. ive been working on other stuff recently, you can find the new repos [here](https://github.com/DarkThemeHub) to see if any is of interest.

 Google darktheme still needs some fixes but im curious to how it looks or if it works at all on mobile.

**Comment by Akianonymus** [comment]
@Snazzie Well, as you said in the last sentence, no userstyles doesn't apply to me.

I manually download from userstyles though and apply update, it works then.

**Comment by Snazzie** [comment]
Have you tried https://raw.githubusercontent.com/DarkThemeHub/GithubDarkTheme/master/Generated/github.user.styl

As Auto update works via installing from that link on pc.

**Comment by Akianonymus** [comment]
@Snazzie I wish i could test but i need in the form of userscript, sadly the browser i use doesn't have parser to properly convert to usable form. :(

**Comment by Snazzie** [comment]
Does your browser support browser extensions?

**Comment by Snazzie** [comment]
Like if i rolled out a dedicated extension, will it work?

**Comment by Akianonymus** [comment]
@Snazzie My browser supports userscripts ( tampermonkey userscripts )

https://userstyles.org/styles/userjs/168350/githubdarktheme.user.js

like this

also, you don't need to do that much hassle, android already have a browser ( kiwi browser ) which supports chrome extensions.

Also, userscripts in android browsers are almost non-existent.

There must be some tool to convert userstyles ( .styl ) files to userscript, as userstyles.org generate it itself, or maybe a simple program could be written to achieve this.

**Comment by Snazzie** [comment]
Yeah it looks quite straight forward. if chrome extension wont work for you, i may consider whipping up a quick conversion script.

Ive actually already made a chrome extension for this theme. its progress is on pause since my plan is to have a one extension for all themes. but its functional. you wont be able to get it from chrome store since i couldnt be bothered to pursue after they sent me copy paste message twice even after follow up.

https://github.com/DarkThemeHub/GithubDarkTheme/tree/master/Extensions/Chrome

**Comment by Akianonymus** [comment]
> Yeah it looks quite straight forward. if chrome extension wont work for you, i may consider whipping up a quick conversion script.
> 
> Ive actually already made a chrome extension for this theme. its progress is on pause since my plan is to have a one extension for all themes. but its functional. you wont be able to get it from chrome store since i couldnt be bothered to pursue after they sent me copy paste message twice even after follow up.
> 
> https://github.com/DarkThemeHub/GithubDarkTheme/tree/master/Extensions/Chrome

Aah, sad to hear that, and waiting .. :p
