### ISSUE TITLE
Missing spacing below "Submit new issue" button

### ISSUE THREAD

**Issue by sclu1034** [DarkThemeHub/GithubDarkTheme#202]
**Describe the bug**
The "Submit new issue" button when creating an issue is missing spacing at the bottom.

**Expected behavior**
Some clearing between the button and the edge of the background.

**Screenshots**
![image](https://user-images.githubusercontent.com/4508454/99152455-2effb700-26a2-11eb-8d6d-750c6acad255.png)

**Comment by Snazzie** [comment]
Ive had some problems with this specific one. ill give it another look.
Note to self: issue lies around the `*`. can be found when inspecting the element `timeline-comment`
![image](https://user-images.githubusercontent.com/19627023/99340610-3da3c500-2880-11eb-950f-3726057d23ad.png)

**Comment by sclu1034** [comment]
Just had a look myself. This really is a weird one.
Apparently the existence of a non-zero width border on `timeline-comment` determines whether the margins between it and the following `text-small` collapse or stay separate.

Adding `border: 1px solid transparent !important` to `timeline-comment` restores the expected spacing.

**Comment by Snazzie** [comment]
Nice! thanks for looking into it :)
