### ISSUE TITLE
make the script compatible with violentmonkey

### ISSUE THREAD

**Issue by super-lurker** [DarkThemeHub/GithubDarkTheme#206]
can you make the script compatible with violentmonkey or other userscript extension??

**Comment by Snazzie** [comment]
I had requests on doing it, im willing to generate one just need some solid example that i can work with.
Can you find me an example?

**Comment by Snazzie** [comment]
I managed to get the script to run on specific url based on the regex provided. but the styles arent applying :/

**Comment by Snazzie** [comment]
For some reason it wont inject the css
```Js
==UserScript==
@name         GithubDarkTheme();
@namespace    github.com/DarkThemeHub/GithubDarkTheme
@version      0.1
@description  Dark theme for github.
@author       You
@grant        GM_addStyle
@include      /^https?:\/\/(((?!desktop).*\.)?(githubusercontent|githubstatus|github)\.(?!io|myshopify|blog|community)).*/
==/UserScript==

GM_addStyle(`
html {
  background-color: #222; }
`
);
```

**Comment by super-lurker** [comment]
https://userstyles.org/styles/168350/githubdarktheme-see-description-before-install

if you scroll to the bottom of the description, there is an option to install as userscript, thats what im using right now, but i doont thinksd its up to date

**Comment by Snazzie** [comment]
ahh nice, i could easily whip out a script to generate that

**Comment by Snazzie** [comment]
And you're right, i stopped pushing updates to it as the regex interpreter wasnt working with my regex. didnt want to maintain multiple. :)

**Comment by Snazzie** [comment]
Also a big factor to not maintaining that is i cant automate releases to it and the site is slow af :D

**Comment by super-lurker** [comment]
> And you're right, i stopped pushing updates to it as the regex interpreter wasnt working with my regex. didnt want to maintain multiple. :)

most ppl post their scripts here  greasyfork.org and openuserjs.org
I also opt out of stylish after the spyware thing, so i avoid any stylish related stuff like their website, but i made an exception for your script :)

**Comment by Snazzie** [comment]
tried the script from userstyles. doesnt work for me :/

**Comment by super-lurker** [comment]
> tried the script from userstyles. doesnt work for me :/


work for me using violentmonkey  on ungoogled-chromium

**Comment by Snazzie** [comment]
Ok, it seems like tamper monkey doesnt work with it. but yeah it does work with violent monkey. cool

**Comment by Snazzie** [comment]
Enjoy ;) https://github.com/DarkThemeHub/GithubDarkTheme#user-script

![image](https://user-images.githubusercontent.com/19627023/99923111-18a1cd00-2d2c-11eb-8b1d-550ee8f9041c.png)
