### ISSUE TITLE
Thanks mate!

### ISSUE THREAD

**Issue by xcasxcursex** [DarkThemeHub/GithubDarkTheme#210]
Well, today I log into github and there it is - native dark mode!

They took their sweet time, but they got here in the end. Just wanted to say a quick thanks for all the fish :)

**Comment by Snazzie** [comment]
No problem! Personally not a fan of how dark it is, so i won't be using it. Which means this theme will continue to exist along side 🙂

**Comment by xcasxcursex** [comment]
> No problem! Personally not a fan of how dark it is, so i won't be using it. Which means this theme will continue to exist along side 🙂

Yeh and the 'blue on blue on blue-grey' thing... Oof. So many shades of blue. It's a classic fashion faux-pas. Stoked to hear you're sticking around!!

Perhaps you could leverage this new theme as the underlying theme for your work :)
