### ISSUE TITLE
Create theme for ZenHub Extension

### ISSUE THREAD

**Issue by zxeoc** [DarkThemeHub/GithubDarkTheme#216]
**Improvement to be done**
It seems github added some new elements, for example, the "TimelineItem" elements of this page: https://github.com/spring-projects/spring-statemachine/issues/397

**Describe the solution you'd like**
Dark theme, like other elements.

**Comment by Snazzie** [comment]
The issue isnt immediately obvious, Can you provide a screenshot? 

its possible its a new beta roll out and im not on the list :)

**Comment by zxeoc** [comment]
Sure, this is the screenshot:
![image](https://user-images.githubusercontent.com/4046320/104404887-ad8bae80-5596-11eb-88fe-0775188c1596.png)
![image](https://user-images.githubusercontent.com/4046320/104404994-ed529600-5596-11eb-9d07-a66c2fad4866.png)

And more elements on page https://github.com/spring-projects/spring-statemachine/issues/913
![image](https://user-images.githubusercontent.com/4046320/104405035-00656600-5597-11eb-8041-59dd9fc2f094.png)
![image](https://user-images.githubusercontent.com/4046320/104405083-20952500-5597-11eb-840f-bc44d3a34e4a.png)
![image](https://user-images.githubusercontent.com/4046320/104405118-30ad0480-5597-11eb-940a-7e7e7cf064b9.png)

**Comment by Snazzie** [comment]
Ok i found out where this comes from, its ZenHub browser extension.
I'll make an exception for styling it. though you'll have to bug me if it breaks at any point as i wont be continously running the extension. :)

**Comment by zxeoc** [comment]
Wow, I thought it was from Github itself. And yes, I'm using ZenHub. If something breaks, I'll let you know. Thanks.

**Comment by Snazzie** [comment]
I just spent last hour theming ZenHub extension, then i discovered there are so many pages! and within ZenHub's css, they use `!important` in some places which i cant override due to the way the theme is injected. 

Unfortunately theres too much work here to do all of zenhub, but i can theme the PR page elements. Which is what Zenhub currently has themed when switching on Github's native dark theme 

Eventually when they migrate fully to using root variables, i can do the rest.

**Comment by Snazzie** [comment]
i actually also made zenhub projects view presentable and also open PR Modal.

**Comment by Snazzie** [comment]
Just released it. Feel free to increase the coverage yourself  by submitting a PR :)

**Comment by zxeoc** [comment]
It makes the pages much better, thank you.
