### ISSUE TITLE
white background in Dark theme 1.50.1

### ISSUE THREAD

**Issue by tessus** [DarkThemeHub/GithubDarkTheme#225]
**Describe the bug**
Using version 1.50.1.
It seems that gh changed the css classes. Part of the upper menu has now a white background. See screenshot.

**Expected behavior**
The background should be dark, as it was before.

**Screenshots**
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/223439/147605383-87e673b5-82f5-4234-b1eb-fbacaa1594ab.png">

**Comment by Snazzie** [comment]
Thought i was the only one using this theme now. I will fix it just for you my dude!

**Comment by Snazzie** [comment]
Fixed

**Comment by tessus** [comment]
Awesome.

Btw, I can't believe I am the only one who uses the Dark theme. It's the best one out there.
