### ISSUE TITLE
Organisation SSO signin not styled.

### ISSUE THREAD

**Issue by cooperaj** [DarkThemeHub/GithubDarkTheme#94]
**Describe the bug**
When using organisation SSO the login dialog is not styled. It uses a white box and is filled with (styled) white and unreadable text. 

**Expected behavior**
The box should be a dark grey

**Screenshots**
![Screenshot 2019-10-15 11 31 20](https://user-images.githubusercontent.com/400210/66824054-62bc5a80-ef3f-11e9-902d-ad3185746b9b.png)

**Desktop (please complete the following information):**
 - Firefox

**Fix**
Add `.org-sso-panel` at line 1803 giving it a background of `#25272a !important`

**Comment by acoop133** [comment]
Thanks for listing the css class name, it made it very easy to add :)
