### ISSUE TITLE
gh articles use light background color

### ISSUE THREAD

**Issue by tessus** [DarkThemeHub/GithubDarkTheme#96]
**Describe the bug**

Go to a gh article, e.g.: https://help.github.com/en/articles/set-up-git
Top left and right corner are white (or close to white `#fafbfc`).
Responsible code: `<div style="background:#fafbfc;">`

**Expected behavior**

The background should be like the rest of the page.

**Screenshots**

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/223439/67054548-eed2ab80-f112-11e9-8dbd-2c3aee670893.png">

**Desktop (please complete the following information):**
 - Theme version: 1.14.1
 - Browser: Firefox 69.0.3 (macOS)

**Comment by acoop133** [comment]
you're right, though id probably make the whole top bar `#24292E` so its consistent to the rest of the theme.

**Comment by tessus** [comment]
Sure, whatever works to get rid of those white corners ;-)

**Comment by acoop133** [comment]
if you wish to get rid of it right now, just edit the theme and add the following

```
div[style="background:#fafbfc;"] {
	background: unset !important;
}
```

I probably won't be releasing the fix until sunday :^)

**Comment by tessus** [comment]
No worries, no rush. I don't read gh articles very often. It's just something I've noticed.
